### ISSUE TITLE
Is not working when Activity is set to "adjustNothing" in AndroidManifest.xml

### ISSUE THREAD

**Issue by w9xhc** [yshrsmz/KeyboardVisibilityEvent#1]
set Activity "InputMode" like this:
```java
android:windowSoftInputMode="adjustNothing"
```
code will not work.

Do you have any good idea ?

**Comment by yshrsmz** [comment]
Current implementation of detecting keyboard visibility change is to compare the diff of the display height and the activity's actual height.
So if the activity's height does not change, the library will not be able to detect keyboard visibility.

Sorry I can't come up with a solution for now, though any suggestion or PR is welcome.

**Comment by w9xhc** [comment]
Thanks !
