### ISSUE TITLE
support sdk 9(add something like ButterKnife's unbinder)

### ISSUE THREAD

**Issue by yshrsmz** [yshrsmz/KeyboardVisibilityEvent#13]
Currently the library use ActivityLifecycleCallbacks to auto-remove event upon Activity's onDestroy.

but it would be great if we can support sdk 9

maybe ButterKnife style unbinder work?

**Comment by yshrsmz** [comment]
http://jakewharton.github.io/butterknife/#reset

**Comment by anoop44** [comment]
@yshrsmz So, will the method to add listener will remain same? Only change is that the register method will return something that can be used to deregister?

**Comment by yshrsmz** [comment]
@anoop44 yes, what you said is exactly what I think.
And unregister logic using AativityLifecycleCallbacks should be dropped in favor of this feature.

**Comment by anoop44** [comment]
@yshrsmz Will try to come up something of that sort, just to clarify, do you expect that someone might need multiple listeners?

**Comment by yshrsmz** [comment]
I think multiple listeners will be needed if someone tries to register listeners from Conductor's controllers, right?

**Comment by yshrsmz** [comment]
but maybe not needed for initial implementation 😉

**Comment by yshrsmz** [comment]
since sdk 9 is really old, maybe we should recommend users to upgrade sdk version, and keep current min sdk(which is 14)

**Comment by yshrsmz** [comment]
closed by #18

**Comment by anoop44** [comment]
Hi,

When I can expect a release for #18 ?

**Comment by yshrsmz** [comment]
yep, I'm currently working on the release.
sorry to be late

**Comment by yshrsmz** [comment]
released as v2.1.0
