### ISSUE TITLE
Check windowSoftInputMode and throw on registration

### ISSUE THREAD

**Issue by yshrsmz** [yshrsmz/KeyboardVisibilityEvent#19]

**Comment by anoop44** [comment]
hi @yshrsmz 
Can you tell me why this is required? Do you have any specific scenario where it will be required?

**Comment by yshrsmz** [comment]
As KeyboardVisibilityEvent can only work with specifiy windowSoftInputModes, I thought it would be nice if the library notifies user about this limitation.

**Comment by anoop44** [comment]
Got it. If the WindowSoftInputMode is something like `adjustNothing` or `adjustPan` which will not resize the root layout, then throw an exception like `IllegalStateException` or something right?

**Comment by yshrsmz** [comment]
Yes, that is the plan ;)

**Comment by anoop44** [comment]
I hope this can be closed now

**Comment by yshrsmz** [comment]
yes, thanks for your contribution!
