### ISSUE TITLE
How to get keyBoard height?

### ISSUE THREAD

**Issue by VeeraAndroid** [yshrsmz/KeyboardVisibilityEvent#21]
How to get keyboard height? and how to set custom height in softKeyBoard?

**Comment by yshrsmz** [comment]
what you ask is not supported by this library.

maybe [this diff](https://github.com/yshrsmz/KeyboardVisibilityEvent/blob/master/keyboardvisibilityevent/src/main/java/net/yslibrary/android/keyboardvisibilityevent/KeyboardVisibilityEvent.java#L79) is the height, but I'm not sure.

About your second question, I have no idea if it's possible.
