### ISSUE TITLE
Event using the keyboard

### ISSUE THREAD

**Issue by bal194** [yshrsmz/KeyboardVisibilityEvent#28]
Hi

The situation is following. Application A while hanging out in the background. The user enters the SMS messages and calls the keyboard to enter the text.
Can Application A somehow receive an event about the fact of using the keyboard in SMS messages? Application A wants to get only the fact of using the keyboard, without any data.

**Comment by yshrsmz** [comment]
Answer is no.
This library calculate the diff of activity's height, it needs activity to measure.
And I think Application A(your app, right?) can not [attach event](https://github.com/yshrsmz/KeyboardVisibilityEvent/blob/cdf799faa71b3dd0ab7fcc70b90223d05fd94b3d/keyboardvisibilityevent/src/main/java/net/yslibrary/android/keyboardvisibilityevent/KeyboardVisibilityEvent.java#L93) to other app's Activity.

**Comment by bal194** [comment]
That's right, Application A needs to pass the keyboard usage event to another application. This task is in principle solvable? 
I understand that it cannot be done by means of this library.

**Comment by bal194** [comment]
Application A has permission to read SMS-messages. Can Application A see event call keyboard Application sms-messages?

**Comment by yshrsmz** [comment]
This looks like a question rather than a feature request or issue report. 
You'd better ask at StackOverflow, but in general, `Intent` is the way to communicate between Applications.
