### ISSUE TITLE
update to the latest Android Gradle Plugin

### ISSUE THREAD

**Issue by yshrsmz** [yshrsmz/KeyboardVisibilityEvent#29]
we need to migrate to AGP 3.2.0

**Comment by anoop44** [comment]
AGP 3.2.0 requires Gradle distros above 4.6. The latest versions release plugin used in the project (https://github.com/novoda/bintray-release) has an issue from Gradle 4.5 and above for Android project. So the update is kind of blocked on bintray-release. Link to the issue https://github.com/novoda/bintray-release/issues/177

**Comment by yshrsmz** [comment]
That's unfortunate.
I'm going to remove bintray-release for now, and update to AGP3.2.0 anyway.

Looks like they are trying to solve the issue. So I'm going to wait for some days, and if nothing would be happened, I'll move to bintray/gradle-bintray-plugin.
https://github.com/novoda/bintray-release/pull/228

**Comment by anoop44** [comment]
Seems like this fork of bintray-release works. Didn't get time to try
https://github.com/StefMa/bintray-release

**Comment by mr-archano** [comment]
@yshrsmz we have just released a new version of [`novoda/bintray-release`](https://bintray.com/novoda/maven/bintray-release/0.9) that should fix the issue you were facing.
It was a tricky one to fix, it took longer than anticipated. Feel free to give it a go and open an issue if any problem.

**Comment by yshrsmz** [comment]
released v2.2.0 with novoda/bintray-release v0.9
thanks @mr-archano !
