### ISSUE TITLE
SOFT_INPUT_IS_FORWARD_NAVIGATION fires new IllegalArgumentException

### ISSUE THREAD

**Issue by savelyevdm** [yshrsmz/KeyboardVisibilityEvent#37]
Hi!
Thanks for your work to provide the world such a pretty library!

Nevertheless with version 2.2.1 I caught some strange behaviour, which I misunderstood.

I have some Activities with Fragments. Activities have `adjustResize` option enabled.
`KeyboardVisibilityEvent.registerEventListener()` method is called in `onResume()` of fragments lifecycle & is sometimes working fine, but sometimes - is not.

After debugging of this issue I gathered that `activity.getWindow().getAttributes().softInputMode` has `SOFT_INPUT_IS_FORWARD_NAVIGATION` flag sometimes included when onResume() is called, along with expected `SOFT_INPUT_ADJUST_RESIZE` (In other words I receive mode `274` instead of regular mode `18`).
So finally I get an error:
```new IllegalArgumentException("Parameter:activity window SoftInputMethod is not ADJUST_RESIZE")```.

If I am correct - this flag doesn't affect behaviour of the library, so could you please take this flag into consideration & make an update to the library.
Or, please, explain me, how to avoid such an error.

As a workaround I delay the call to `KeyboardVisibilityEvent.registerEventListener()` method by 100ms after onResume() & it works.

**Comment by savelyevdm** [comment]
Any thoughts?

**Comment by yshrsmz** [comment]
Sounds good to me.
Would you like to submit a PR?

2019年3月19日(火) 1:04 Daniil Savelyev <notifications@github.com>:

**Comment by jemshit** [comment]
This happens on v2.2.1, but there was not such problem in  v2.1.0,

**Comment by yshrsmz** [comment]
I've just released v2.3.0 which includes a change which possibly fix this issue.

**Comment by aayushthakur** [comment]
This same thing was happening with me but the problem was I never faced it during debugging, it was always reported to me by CrashLytics app which didn't give a clear error reason as to why this was happening. Can you tell me what did u do to fix this issue @yshrsmz ?

**Comment by yshrsmz** [comment]
https://github.com/yshrsmz/KeyboardVisibilityEvent/pull/39/files

This is the PR that should have fixed the issue.
