### ISSUE TITLE
KeyboardVisibilityEvent Status is open on devices having big status bar

### ISSUE THREAD

**Issue by deepak786** [yshrsmz/KeyboardVisibilityEvent#41]
With Android 9 on some devices, the status bar height is large so the event listener for KetboardVisibilityEvent is always open.

Here is the attached screenshot of the device emulator having the big status bar:
![device-2019-07-05-144756](https://user-images.githubusercontent.com/14223997/60712097-e5db1700-9f33-11e9-985b-92e8047b353a.png)

I tried to get the values of Screen Height, Height Difference, Status Bar, etc and here are the results:
1. ScreenHeight = 1920
2. StatusBarHeight = 171
3. Rectangle = Rect(0, 171 - 1080, 1794)
4. HeightDifference = 297
5. KeyboardMinHeight = ScreenHeight * KeyboardMinRatio = 1920*0.15 = 288

As you can see that the HeightDifference is bigger than KeyboardMinHeight. Due to this the status is always open.

I think we need to include status bar height in calculation to make it work.
Can you please check?

Let me know if you need more details

Thanks

**Comment by yshrsmz** [comment]
Sounds reasonable 👍 
It would be great if the library can handle different size of status/navigation bar.
Would you like to submit a PR?

**Comment by deepak786** [comment]
#42 Solved the issue for me. Thanks @arquimago

**Comment by yshrsmz** [comment]
I've just released 3.0.0-RC1 with the fix for this issue.
Please let me know if it works or not :pray:
