### ISSUE TITLE
setEventListener leaks fragment

### ISSUE THREAD

**Issue by kletzander** [yshrsmz/KeyboardVisibilityEvent#48]
When calling setEventListener from fragment instance the listener does not get unregistered when the fragment is destroyed. The reason is simple - this library registers activity lifecycle observer, but the activity outlives fragments.

At minimum this causes fragment leak, in worst case scenario it causes application crash in case the event listener touches dead fragment views/data bindings.

What we would like to have added is to use Architecture Components lifecycle support, so in addition to activity there would be a `LifecycleOwner` passed to `setEventListener` where you can then observe its lifecycle and unregister the listener automatically when the owner is destroyed, be it `Activity` or `Fragment`.

For now the workaround is to manually unregister the listener in corresponding Fragment's lifecycle methods.

**Comment by yshrsmz** [comment]
That sounds really nice!
Would you like to send a PR?

**Comment by kletzander** [comment]
Yeah, I can definitely contribute if you don't mind adding new dependency to lifecycle architecture components.

**Comment by yshrsmz** [comment]
AppCompat has a dependency on AndroidX Lifecycle, and there are few apps without it(I guess), so let's do it 😄

**Comment by kletzander** [comment]
I have created the following PR. However I'm not sure about all the bells and whistles around bumping version numbers, publishing, etc. Can you please help me?
