### ISSUE TITLE
Readme needs Update: getLifecycleOwner(), is not an argument for setEventListener

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [yshrsmz/KeyboardVisibilityEvent#60]
As Described in the Readme:
```
KeyboardVisibilityEvent.setEventListener(
        getActivity(),
        getLifecycleOwner(),
        new KeyboardVisibilityEventListener() {
            @Override
            public void onVisibilityChanged(boolean isOpen) {
                // some code depending on keyboard visiblity status
            }
        });
```
LifeCycleOwner is not an option in the method. Can you please explain why it is removed?

**Comment by yshrsmz** [comment]
https://github.com/yshrsmz/KeyboardVisibilityEvent/blob/ad77fb4b860773ade6bf2c874f20b5eb3216317e/keyboardvisibilityevent/src/main/java/net/yslibrary/android/keyboardvisibilityevent/KeyboardVisibilityEvent.kt#L33-L47

Which version are you using? Please use 3.0.0-RC2

**Comment by Morteza-Rastgoo** [comment]
It was 2.3.0
Let me try 3.0.0-RC2.

**Comment by Morteza-Rastgoo** [comment]
Thanks this is fine with the 3.0.0-RC2.

**Comment by yshrsmz** [comment]
Thanks for the confirmation!

Maybe I should release 3.0.0.

**Comment by Morteza-Rastgoo** [comment]
Sounds Good.

**Comment by Morteza-Rastgoo** [comment]
Can I ask an Irrelevant question?
In a Fragment, I have 4 editTexts which `I don't want to get Automatic focus` when page opens or onResume `In One Of the editTexts`.
The only working solution to avoid keyboard opening onResume is to use this library and close the keyboard if focus is on one of editTexts that I don't want to get keyboard opened.
Is there any other solution to this?
