### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by esdrasdl** [yshrsmz/KeyboardVisibilityEvent#64]
[Starting from May 1, 2021 JCenter will stop working](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Do you publish only to JCenter? Are there any plans to move away?

**Comment by yshrsmz** [comment]
Yes, I'm planning to publish the most recent version of this lib to Maven Central, though I can't tell you the ETA.
But I'm sure I can do this until May 1.

**Comment by barnhill** [comment]
Do you already have a Sonatype account for publishing to maven central?  If so would you be open to a PR to help with this?  Not committing to anything yet but just curious.

**Comment by yshrsmz** [comment]
@barnhill 
Yes, I have a Sonatype account. Actually, this lib was once distributed from Maven Central.

Regarding contribution, of course, I really appreciate it if you can send a PR!
I've already migrated one of my libs with [vanniktech/gradle-maven-publish-plugin](https://github.com/vanniktech/gradle-maven-publish-plugin), and was really easy. 

So please use [vanniktech/gradle-maven-publish-plugin](https://github.com/vanniktech/gradle-maven-publish-plugin) when you create a PR.

**Comment by barnhill** [comment]
K will do in the next few days.  I'll have to have you test with your sonatyoe account once it's up there.

**Comment by barnhill** [comment]
@yshrsmz and @esdrasdl have a look at the PR and see if it works for publishing to MavenCentral.  I cant test it since I dont have the correct credentials but should be easy enough to test.

**Comment by yshrsmz** [comment]
FYI I've just uploaded all releases to Maven Central.
https://repo1.maven.org/maven2/net/yslibrary/keyboardvisibilityevent/keyboardvisibilityevent/

**Comment by barnhill** [comment]
@yshrsmz thank you!!
