### ISSUE TITLE
Tablet Devices: not working

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [yshrsmz/KeyboardVisibilityEvent#7]
not working in SGH and other Tablets ...I have test and perfectly work on Samsungh Device S4, but the same example not work on SGH Tablet 7" and 10" and also Huawei and China Devices

**Comment by yshrsmz** [comment]
Thank you for reporting, Actually I haven't tested on tablet devices. Will look into it.

**Comment by abdulrahmanmajeed** [comment]
Thanks a lot buddy ..

**Comment by yshrsmz** [comment]
PR is welcome, by the way ;)

**Comment by UsherBaby** [comment]
@abdulrahmanmajeed 
Fix solution : 
public static void hideKeyboard(Activity activity) {
-        View view = activity.getCurrentFocus();
+        View view = activity.getWindow().getDecorView();

**Comment by yshrsmz** [comment]
closed via #16
