### ISSUE TITLE
Not working with DialogActvity

### ISSUE THREAD

**Issue by JitenNumberTank** [yshrsmz/KeyboardVisibilityEvent#8]
I have used windowSoftInputMode is adjustResize and my android os version 5.0 and device is Nexus 5. I am getting IsOpen true or false in normal activity. but If I use Theme.dialog for Activity means DialogActvity then its not working in my case

**Comment by UsherBaby** [comment]
@JitenNumberTank 
Fix solution :
Use "View view = activity.getWindow().getDecorView()" instead of "View view = activity.getCurrentFocus()" in method UIUtil.hideKeyboard(Activity activity)
